# Generated by Django 4.2.1 on 2023-06-27 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name=uuid.uuid4),
        ),
    ]
