# Generated by Django 4.2.1 on 2023-06-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvariant_sizevariant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_variant',
        ),
        migrations.DeleteModel(
            name='ColorVariant',
        ),
    ]
